/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  games_list: () => import("@/views/games/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  management: () => import("@/views/management/_route/index.vue"),
  "management_audit-log": () => import("@/views/management/audit-log/index.vue"),
  management_company: () => import("@/views/management/company/index.vue"),
  "management_email-settings": () => import("@/views/management/email-settings/index.vue"),
  "management_game-instance": () => import("@/views/management/game-instance/index.vue"),
  management_games: () => import("@/views/management/games/index.vue"),
  management_member: () => import("@/views/management/member/index.vue"),
  "management_play-attempts": () => import("@/views/management/play-attempts/index.vue"),
  management_scores: () => import("@/views/management/scores/index.vue"),
  "management_budget-tracking": () => import("@/views/management/budget-tracking/index.vue"),
  management_permission: () => import("@/views/management/permission/index.vue"),
  management_role: () => import("@/views/management/role/index.vue"),
  management_user: () => import("@/views/management/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
