/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "games_budget-tracking": () => import("@/views/games/budget-tracking/index.vue"),
  "games_game-instance": () => import("@/views/games/game-instance/index.vue"),
  games_list: () => import("@/views/games/list/index.vue"),
  "games_member-detail": () => import("@/views/games/member-detail/[id].vue"),
  games_members: () => import("@/views/games/members/index.vue"),
  "games_play-attempts": () => import("@/views/games/play-attempts/index.vue"),
  "games_prize-types": () => import("@/views/games/prize-types/index.vue"),
  games_prizes: () => import("@/views/games/prizes/index.vue"),
  games_scores: () => import("@/views/games/scores/index.vue"),
  "games_theme-detail": () => import("@/views/games/theme-detail/index.vue"),
  games_themes: () => import("@/views/games/themes/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "management_audit-log": () => import("@/views/management/audit-log/index.vue"),
  management_company: () => import("@/views/management/company/index.vue"),
  "management_email-settings": () => import("@/views/management/email-settings/index.vue"),
  management_games: () => import("@/views/management/games/index.vue"),
  "management_sync-settings": () => import("@/views/management/sync-settings/index.vue"),
  management_permission: () => import("@/views/management/permission/index.vue"),
  management_role: () => import("@/views/management/role/index.vue"),
  management_user: () => import("@/views/management/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
