/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'games',
    path: '/games',
    component: 'layout.base',
    meta: {
      title: 'games',
      i18nKey: 'route.games',
      icon: 'ion:game-controller',
      order: 1
    },
    children: [
      {
        name: 'games_list',
        path: '/games/list',
        component: 'view.games_list',
        meta: {
          title: 'games_list',
          i18nKey: 'route.games_list',
          roles: ['R_SUPER', 'R_ADMIN', 'R_USER'],
          icon: 'ion:game-controller-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'management',
    path: '/management',
    component: 'layout.base',
    meta: {
      title: 'management',
      i18nKey: 'route.management',
      icon: 'carbon:cloud-service-management',
      order: 2
    },
    children: [
      {
        name: 'management_audit-log',
        path: '/management/audit-log',
        component: 'view.management_audit-log',
        meta: {
          title: 'management_audit-log',
          i18nKey: 'route.management_audit-log',
          roles: 'audit-logs:read'
        }
      },
      {
        name: 'management_company',
        path: '/management/company',
        component: 'view.management_company',
        meta: {
          title: 'management_company',
          i18nKey: 'route.management_company',
          roles: ['R_SUPER'],
          icon: 'carbon:enterprise',
          order: 1
        }
      },
      {
        name: 'management_email-settings',
        path: '/management/email-settings',
        component: 'view.management_email-settings',
        meta: {
          title: 'management_email-settings',
          i18nKey: 'route.management_email-settings',
          roles: ['R_SUPER'],
          icon: 'carbon:email',
          order: 3
        }
      },
      {
        name: 'management_game-instance',
        path: '/management/game-instance',
        component: 'view.management_game-instance',
        meta: {
          title: 'management_game-instance',
          i18nKey: 'route.management_game-instance'
        }
      },
      {
        name: 'management_member',
        path: '/management/member',
        component: 'view.management_member',
        meta: {
          title: 'management_member',
          i18nKey: 'route.management_member'
        }
      },
      {
        name: 'management_permission',
        path: '/management/permission',
        component: 'view.management_permission',
        meta: {
          title: 'management_permission',
          i18nKey: 'route.management_permission',
          roles: ['R_SUPER'],
          icon: 'carbon:user-access',
          order: 4
        }
      },
      {
        name: 'management_role',
        path: '/management/role',
        component: 'view.management_role',
        meta: {
          title: 'management_role',
          i18nKey: 'route.management_role',
          roles: ['R_SUPER', 'R_ADMIN'],
          icon: 'carbon:user-role',
          order: 2
        }
      },
      {
        name: 'management_user',
        path: '/management/user',
        component: 'view.management_user',
        meta: {
          title: 'management_user',
          i18nKey: 'route.management_user',
          roles: ['R_SUPER', 'R_ADMIN'],
          icon: 'ph:users',
          order: 3
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
